### ISSUE TITLE
Multiple machines

### ISSUE THREAD

**Issue by octavioturra** [ericholiveira/studio#37]
I think it's not clear how I can configure each actor to work in an exclusive machine, then connect all. 
Is there a way to configure this architecture?

**Comment by ericholiveira** [comment]
Hey @octavioturra ... Yes and no...
On versions 0.10.X you can use the experimental https://github.com/ericholiveira/studio-cluster which enables you to do this without any configuration as long all machines are in the same network.

But, starting on versions 0.11.X i've started to rebuild studio to reduce the amount of boilerplate and make easier to understand the concepts, most of the features of older versions are already implemented but not the rpc/cluster... I will be updating the readme with the new names and api.  So if youre enjoyed the idea behind Studio and wants to try it... i would ask you to wait for the new readme so you can understand how things works on this new version.

Ive also plan to implement the rpc/cluster/multiple machines for the new versions support until next friday...

**Comment by ericholiveira** [comment]
Updated

**Comment by ericholiveira** [comment]
@octavioturra you can see the cluster module in https://www.npmjs.com/package/studio-cluster

This module will be under heavy development for the next weeks, if you still have interest on it, just watch. The module isnt production-ready yet, i still need to do several tests, but you can have a glance on how it will work. 
On the repository there is a basic example on how to configurate it (actually no configuration is required, just add a plugin)
