### ISSUE TITLE
Is there anyway to create services across different node apps?

### ISSUE THREAD

**Issue by pajtai** [ericholiveira/studio#38]
Nice library. Was wondering if you could use it to communicate between multiple apps?

**Comment by pajtai** [comment]
Just going through the README again, and I see the info about clustering now:

https://github.com/ericholiveira/studio#cluster

So with the [studio-cluster](https://github.com/ericholiveira/studio-cluster) plugin this is possible.

Thanks

**Comment by ericholiveira** [comment]
Yes... you can see examples some basic examples at: https://github.com/ericholiveira/studio-cluster/tree/master/examples

And im starting a more in deep explanation at my medium: https://medium.com/@ericholiveira/nodejs-microservices-from-zero-to-hero-pt1-279548cb4080
