### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by sean-hill** [ericholiveira/studio#43]
Hey I was just curious what a good file structure would be for use with Studio and an Express API. I'm thinking something like this:

	- services
		- config-service.js
		- user-module
			- index.js
			- create-service.js
			- update-service.js
			- remove-service.js
		- auth-module
			- index.js
			- signup-service.js
			- login-service.js

	- api
		- user-routes
			- index.js
			- create-route.js
			- update-route.js
			- etc.
	- app
		- index.js

Under the services folder, they are group by Studio module's if appropriate, or just standalone files if the service doesn't need a module. Then each api route would have its own file, which would then require its associated service.

Thoughts? Also, what have you guys done?

**Comment by sean-hill** [comment]
Another idea, would be to group services and routes together like:

	- app
		index.js
		- user
			index.js
			- create
				- service.js
				- route.js
			- update
				- service.js
				- route.js

But I don't really like that approach as much.

**Comment by ericholiveira** [comment]
I usually take a slightly diferent approach than 2 . i do the following:

- app
   index.js
   - foo
      index.js
      services.js
      route.js
   - bar
     index.js
     services.js
     route.js

Im using node4 so i just implement my services in a class and use Studio.serviceClass to load it all. If it happens of the service become really big, then you can break it in more subfolders, but for me, it is working really well this way.

This approach (as the second you discribed) has the advantage of being really easy to distribute, if i need different deploys for my services i could do the following

- app
   load_foo.js
   load_bar.js
       -  foo
        .....
      - bar
      .....

Just a minor change and are ready to distribute by functionality

**Comment by sean-hill** [comment]
Hey @ericholiveira!

Thanks. Would you mind screenshotting your file structure as an example? I'm a little confused at what you mean. Thanks :)

**Comment by sean-hill** [comment]
Also I don't see any docs for `Studio.serviceClass` in the repo.

**Comment by ericholiveira** [comment]
Oh, thx i will add it tonight. Anyway you can see it here:
https://medium.com/adopting-microservices-architecture/nodejs-microservices-from-zero-to-hero-pt2-72fbb2a1b1c4#.dahyaklx5

 (I will keep the issue open for a while if anyone wants to comment something on this )

**Comment by ericholiveira** [comment]
Something like this (attaching this, because i only have my company code, so i prefer to avoid printing it) , on express.js i initialize express to use on the routes
![captura de tela 2016-05-11 as 15 40 39](https://cloud.githubusercontent.com/assets/1219172/15192281/e5b66444-178e-11e6-9756-7d95d212123c.png)
