### ISSUE TITLE
Studio agent CLI - monitor/start/stop microservices

### ISSUE THREAD

**Issue by avishnyak** [ericholiveira/studio#50]
We should have an agent service that can be used to monitor services and control up/down state.

Acceptance Criteria:

- I should be able to install the CLI both globally and locally (like grunt/gulp)
- I should be able to provide a config file for all options (this will help the devops story)
- I should be able to start/stop/monitor multiple services on the same machine
- The agent should work at least on Windows, OS X and Linux
- I should be able to start a cluster of services with a single command
- I should be able to start/stop/monitor remote services

@ericholiveira Would you prefer a configuration or code approach (e.g. like grunt or like gulp) for the config file?

**Comment by ericholiveira** [comment]
I prefer a configuration approach...
I would add some criterias:
- Minimal possible changes on studio (the core project)
- Another repository/ npm package
- I should be able to start/stop/monitor multiple services on the same machine in one or different process.

**Comment by avishnyak** [comment]
Ok. I'll create a repo and get started.

**Comment by avishnyak** [comment]
RE: Integrate into Studio with minimal changes to core.

@ericholiveira What do you think of the cli launching studio services with a specific ENV variable set which Studio just 'use'es when it bootstraps?

Pseudo-code:

Studio-cli - Launch child process with ```STUDIO_ADDONS="path_to_file.js;..."```
Studio.js - After bootstrap, require(env.STUDIO_ADDONS); Studio.use(STUDIO_ADDONS);

That would be all the changes needed in core because studio-cli can inject middleware into the launched process which does everything it needs in terms of control and monitoring.

**Comment by ericholiveira** [comment]
Im ok with this, as discussed on slack

**Comment by ericholiveira** [comment]
Closing it as @avishnyak have been working on this here: https://github.com/avishnyak/studio-cli
