### ISSUE TITLE
statsd example

### ISSUE THREAD

**Issue by sean-hill** [ericholiveira/studio#55]
I'd love to see an example of how to use the timer plugin with statsd, thanks :)

**Comment by ericholiveira** [comment]
Its insanely easy... basically copy and pasted from a project of mine...

```js
var StatsD = require('node-statsd'),
    options = require('../conf').get('statsd'),
    os = require('os');

options.prefix = `${os.hostname().replace(/\./g,'_')}.${options.prefix}`;

var statsD =  new StatsD(options);

Studio.use(Studio.plugin.timer(function(res){
    var id = res.receiver.replace(/\//g,'.');
    if(res.err){
        id += '.error';
    }
    statsD.timing('services.'+id,res.time);
}));
```

I use it only for timing purposes... and studio timer already calculate and gives it for you.

Closing for now... reach me if needs to reopen

**Comment by sean-hill** [comment]
Thanks @ericholiveira. You're awesome. I guess the hard part is actually setting up statsd 😬

**Comment by ericholiveira** [comment]
oh yes... sometimes configuring statsd might be a pain in the ass
