### ISSUE TITLE
How to use plugins

### ISSUE THREAD

**Issue by sean-hill** [ericholiveira/studio#56]
Hey @ericholiveira,

The docs about how to create a plugin are a little unclear. I'm trying to just create one that logs the response of all services, just to get started. Here's what I have so far (copied from one of the example plugins and modified a bit).

```js
module.exports = function (options) {
  'use strict'
  console.log('Plugin loaded')
  options.onStart(function (serv) {
    console.log('Plugin started')
    var _fn = serv.fn
    serv.fn = function () {
      var args = arguments
      return _fn.apply(serv, args).then((res) => {
        console.log('Response:', res)
        return res
      })
    }
  })
}
```

I then initiate it with:

```js
Studio.use(require('/path/to/plugin')
```

The log `Plugin loaded` is fired, but `Plugin started` is never fired when I use one of my services, neither is `Response: <service response>`.

I'm just curious how to actually make a plugin. It seems like the boilerplate code is a bit much to create one.

**Comment by sean-hill** [comment]
Oh nvm, lol. It's because I'm trying to access a service created in another network using Studio cluster. It appears I have to require the plugin in both networks.

**Comment by ericholiveira** [comment]
Yes... plugins works only locally
Em 18/06/2016 6:01 PM, "Sean Hill" <notifications@github.com> escreveu:
